name        : wireless-tools
version     : 29
release     : 3
source      :
    - http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/wireless_tools.29.tar.gz : 6fb80935fe208538131ce2c4178221bab1078a1656306bce8909c19887e2e5a1
homepage    : http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Tools.html
license     :
    - GPLv2
summary     : Tools to configure wireless lan cards
component   : network.base
description : |
    The Wireless Tools (WT) is a set of tools allowing to manipulate the Wireless Extensions, a generic application programming interface allowing a driver to expose to the user space configuration and statistics specific to common Wireless LANs. They use a textual interface and are rather crude, but aim to support the full Wireless Extension.
setup      : |
    %patch -p1 < $pkgfiles/disable_ldconfig_in_build.patch
build      : |
    %make
install    : |
    %make_install PREFIX=$installdir/usr MAN_DIR=$installdir/usr/share/man
