name       : wireless-tools
version    : '29'
release    : 5
source     :
    - https://github.com/HewlettPackard/wireless-tools/archive/v29.tar.gz : 69c5face9ac9d3273042436408a9a057d3416a814253dedeaaef210fcbc42d40
homepage   : http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Tools.html
license    : GPL-2.0-or-later
summary    : Tools to configure wireless lan cards
component  : network.base
description: |
    The Wireless Tools (WT) is a set of tools allowing to manipulate the Wireless Extensions, a generic application programming interface allowing a driver to expose to the user space configuration and statistics specific to common Wireless LANs. They use a textual interface and are rather crude, but aim to support the full Wireless Extension.
setup      : |
    cd wireless_tools
    %patch -p1 < $pkgfiles/disable_ldconfig_in_build.patch
build      : |
    %make -C wireless_tools
install    : |
    %make_install -C wireless_tools PREFIX=$installdir/usr INSTALL_MAN=$installdir/usr/share/man
